### ISSUE TITLE
Cannot identify image file.

### ISSUE THREAD

**Issue by Purple-Palm** [seblful/label-studio-yolov8-backend#7]
Hi!
When trying to upload image in LS, I am getting an error in docker terminal.

```
yolo  | Task type is detection.
yolo  | Loading image from: /root/.cache/label-studio/20c0e292__13445cd4-Sample1.jpg
yolo  | Traceback (most recent call last):
yolo  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f                                                                                              
yolo  |     return f(*args, **kwargs)
yolo  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/api.py", line 69, in _predict                                                                                                        
yolo  |     response = model.predict(tasks, context=context, **params)
yolo  |   File "/app/model.py", line 66, in predict                                                                                                                                                          
yolo  |     predictions = self.predict_det(tasks)
yolo  |   File "/app/model.py", line 83, in predict_det                                                                                                                                                      
yolo  |     image = self.load_image(task=task)
yolo  |   File "/app/model.py", line 52, in load_image                                                                                                                                                       
yolo  |     image = Image.open(file_path)                                                                                                                                                                    
yolo  |   File "/opt/conda/lib/python3.10/site-packages/PIL/Image.py", line 3339, in open                                                                                                                    
yolo  |     raise UnidentifiedImageError(msg)                                                                                                                                                                
yolo  | PIL.UnidentifiedImageError: cannot identify image file '/root/.cache/label-studio/20c0e292__13445cd4-Sample1.jpg'
```

Have no idea how to fix that.

**Comment by iamxiaojianzheng** [comment]
The image itself is likely already damaged.
